// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UpLoad.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_UpLoad_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_UpLoad_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_UpLoad_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_UpLoad_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_UpLoad_2eproto;
class UpLoadEchoRequest;
struct UpLoadEchoRequestDefaultTypeInternal;
extern UpLoadEchoRequestDefaultTypeInternal _UpLoadEchoRequest_default_instance_;
class UpLoadEchoResponse;
struct UpLoadEchoResponseDefaultTypeInternal;
extern UpLoadEchoResponseDefaultTypeInternal _UpLoadEchoResponse_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::UpLoadEchoRequest* Arena::CreateMaybeMessage<::UpLoadEchoRequest>(Arena*);
template<> ::UpLoadEchoResponse* Arena::CreateMaybeMessage<::UpLoadEchoResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class UpLoadEchoRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:UpLoadEchoRequest) */ {
 public:
  inline UpLoadEchoRequest() : UpLoadEchoRequest(nullptr) {}
  ~UpLoadEchoRequest() override;
  explicit PROTOBUF_CONSTEXPR UpLoadEchoRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UpLoadEchoRequest(const UpLoadEchoRequest& from);
  UpLoadEchoRequest(UpLoadEchoRequest&& from) noexcept
    : UpLoadEchoRequest() {
    *this = ::std::move(from);
  }

  inline UpLoadEchoRequest& operator=(const UpLoadEchoRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpLoadEchoRequest& operator=(UpLoadEchoRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UpLoadEchoRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const UpLoadEchoRequest* internal_default_instance() {
    return reinterpret_cast<const UpLoadEchoRequest*>(
               &_UpLoadEchoRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(UpLoadEchoRequest& a, UpLoadEchoRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(UpLoadEchoRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UpLoadEchoRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UpLoadEchoRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UpLoadEchoRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UpLoadEchoRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const UpLoadEchoRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UpLoadEchoRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "UpLoadEchoRequest";
  }
  protected:
  explicit UpLoadEchoRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUsernameFieldNumber = 1,
    kTokenFieldNumber = 2,
  };
  // string username = 1;
  void clear_username();
  const std::string& username() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_username(ArgT0&& arg0, ArgT... args);
  std::string* mutable_username();
  PROTOBUF_NODISCARD std::string* release_username();
  void set_allocated_username(std::string* username);
  private:
  const std::string& _internal_username() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_username(const std::string& value);
  std::string* _internal_mutable_username();
  public:

  // string token = 2;
  void clear_token();
  const std::string& token() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_token(ArgT0&& arg0, ArgT... args);
  std::string* mutable_token();
  PROTOBUF_NODISCARD std::string* release_token();
  void set_allocated_token(std::string* token);
  private:
  const std::string& _internal_token() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_token(const std::string& value);
  std::string* _internal_mutable_token();
  public:

  // @@protoc_insertion_point(class_scope:UpLoadEchoRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr username_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr token_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_UpLoad_2eproto;
};
// -------------------------------------------------------------------

class UpLoadEchoResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:UpLoadEchoResponse) */ {
 public:
  inline UpLoadEchoResponse() : UpLoadEchoResponse(nullptr) {}
  ~UpLoadEchoResponse() override;
  explicit PROTOBUF_CONSTEXPR UpLoadEchoResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UpLoadEchoResponse(const UpLoadEchoResponse& from);
  UpLoadEchoResponse(UpLoadEchoResponse&& from) noexcept
    : UpLoadEchoResponse() {
    *this = ::std::move(from);
  }

  inline UpLoadEchoResponse& operator=(const UpLoadEchoResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpLoadEchoResponse& operator=(UpLoadEchoResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UpLoadEchoResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const UpLoadEchoResponse* internal_default_instance() {
    return reinterpret_cast<const UpLoadEchoResponse*>(
               &_UpLoadEchoResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(UpLoadEchoResponse& a, UpLoadEchoResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(UpLoadEchoResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UpLoadEchoResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UpLoadEchoResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UpLoadEchoResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UpLoadEchoResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const UpLoadEchoResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UpLoadEchoResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "UpLoadEchoResponse";
  }
  protected:
  explicit UpLoadEchoResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kUsernameFieldNumber = 4,
    kUseridFieldNumber = 3,
    kSuccessFieldNumber = 1,
    kCodeFieldNumber = 5,
  };
  // string message = 2;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // string username = 4;
  void clear_username();
  const std::string& username() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_username(ArgT0&& arg0, ArgT... args);
  std::string* mutable_username();
  PROTOBUF_NODISCARD std::string* release_username();
  void set_allocated_username(std::string* username);
  private:
  const std::string& _internal_username() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_username(const std::string& value);
  std::string* _internal_mutable_username();
  public:

  // int64 userid = 3;
  void clear_userid();
  int64_t userid() const;
  void set_userid(int64_t value);
  private:
  int64_t _internal_userid() const;
  void _internal_set_userid(int64_t value);
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // int32 code = 5;
  void clear_code();
  int32_t code() const;
  void set_code(int32_t value);
  private:
  int32_t _internal_code() const;
  void _internal_set_code(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:UpLoadEchoResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr username_;
  int64_t userid_;
  bool success_;
  int32_t code_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_UpLoad_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UpLoadEchoRequest

// string username = 1;
inline void UpLoadEchoRequest::clear_username() {
  username_.ClearToEmpty();
}
inline const std::string& UpLoadEchoRequest::username() const {
  // @@protoc_insertion_point(field_get:UpLoadEchoRequest.username)
  return _internal_username();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void UpLoadEchoRequest::set_username(ArgT0&& arg0, ArgT... args) {
 
 username_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:UpLoadEchoRequest.username)
}
inline std::string* UpLoadEchoRequest::mutable_username() {
  std::string* _s = _internal_mutable_username();
  // @@protoc_insertion_point(field_mutable:UpLoadEchoRequest.username)
  return _s;
}
inline const std::string& UpLoadEchoRequest::_internal_username() const {
  return username_.Get();
}
inline void UpLoadEchoRequest::_internal_set_username(const std::string& value) {
  
  username_.Set(value, GetArenaForAllocation());
}
inline std::string* UpLoadEchoRequest::_internal_mutable_username() {
  
  return username_.Mutable(GetArenaForAllocation());
}
inline std::string* UpLoadEchoRequest::release_username() {
  // @@protoc_insertion_point(field_release:UpLoadEchoRequest.username)
  return username_.Release();
}
inline void UpLoadEchoRequest::set_allocated_username(std::string* username) {
  if (username != nullptr) {
    
  } else {
    
  }
  username_.SetAllocated(username, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (username_.IsDefault()) {
    username_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:UpLoadEchoRequest.username)
}

// string token = 2;
inline void UpLoadEchoRequest::clear_token() {
  token_.ClearToEmpty();
}
inline const std::string& UpLoadEchoRequest::token() const {
  // @@protoc_insertion_point(field_get:UpLoadEchoRequest.token)
  return _internal_token();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void UpLoadEchoRequest::set_token(ArgT0&& arg0, ArgT... args) {
 
 token_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:UpLoadEchoRequest.token)
}
inline std::string* UpLoadEchoRequest::mutable_token() {
  std::string* _s = _internal_mutable_token();
  // @@protoc_insertion_point(field_mutable:UpLoadEchoRequest.token)
  return _s;
}
inline const std::string& UpLoadEchoRequest::_internal_token() const {
  return token_.Get();
}
inline void UpLoadEchoRequest::_internal_set_token(const std::string& value) {
  
  token_.Set(value, GetArenaForAllocation());
}
inline std::string* UpLoadEchoRequest::_internal_mutable_token() {
  
  return token_.Mutable(GetArenaForAllocation());
}
inline std::string* UpLoadEchoRequest::release_token() {
  // @@protoc_insertion_point(field_release:UpLoadEchoRequest.token)
  return token_.Release();
}
inline void UpLoadEchoRequest::set_allocated_token(std::string* token) {
  if (token != nullptr) {
    
  } else {
    
  }
  token_.SetAllocated(token, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (token_.IsDefault()) {
    token_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:UpLoadEchoRequest.token)
}

// -------------------------------------------------------------------

// UpLoadEchoResponse

// bool success = 1;
inline void UpLoadEchoResponse::clear_success() {
  success_ = false;
}
inline bool UpLoadEchoResponse::_internal_success() const {
  return success_;
}
inline bool UpLoadEchoResponse::success() const {
  // @@protoc_insertion_point(field_get:UpLoadEchoResponse.success)
  return _internal_success();
}
inline void UpLoadEchoResponse::_internal_set_success(bool value) {
  
  success_ = value;
}
inline void UpLoadEchoResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:UpLoadEchoResponse.success)
}

// string message = 2;
inline void UpLoadEchoResponse::clear_message() {
  message_.ClearToEmpty();
}
inline const std::string& UpLoadEchoResponse::message() const {
  // @@protoc_insertion_point(field_get:UpLoadEchoResponse.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void UpLoadEchoResponse::set_message(ArgT0&& arg0, ArgT... args) {
 
 message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:UpLoadEchoResponse.message)
}
inline std::string* UpLoadEchoResponse::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:UpLoadEchoResponse.message)
  return _s;
}
inline const std::string& UpLoadEchoResponse::_internal_message() const {
  return message_.Get();
}
inline void UpLoadEchoResponse::_internal_set_message(const std::string& value) {
  
  message_.Set(value, GetArenaForAllocation());
}
inline std::string* UpLoadEchoResponse::_internal_mutable_message() {
  
  return message_.Mutable(GetArenaForAllocation());
}
inline std::string* UpLoadEchoResponse::release_message() {
  // @@protoc_insertion_point(field_release:UpLoadEchoResponse.message)
  return message_.Release();
}
inline void UpLoadEchoResponse::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (message_.IsDefault()) {
    message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:UpLoadEchoResponse.message)
}

// int64 userid = 3;
inline void UpLoadEchoResponse::clear_userid() {
  userid_ = int64_t{0};
}
inline int64_t UpLoadEchoResponse::_internal_userid() const {
  return userid_;
}
inline int64_t UpLoadEchoResponse::userid() const {
  // @@protoc_insertion_point(field_get:UpLoadEchoResponse.userid)
  return _internal_userid();
}
inline void UpLoadEchoResponse::_internal_set_userid(int64_t value) {
  
  userid_ = value;
}
inline void UpLoadEchoResponse::set_userid(int64_t value) {
  _internal_set_userid(value);
  // @@protoc_insertion_point(field_set:UpLoadEchoResponse.userid)
}

// string username = 4;
inline void UpLoadEchoResponse::clear_username() {
  username_.ClearToEmpty();
}
inline const std::string& UpLoadEchoResponse::username() const {
  // @@protoc_insertion_point(field_get:UpLoadEchoResponse.username)
  return _internal_username();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void UpLoadEchoResponse::set_username(ArgT0&& arg0, ArgT... args) {
 
 username_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:UpLoadEchoResponse.username)
}
inline std::string* UpLoadEchoResponse::mutable_username() {
  std::string* _s = _internal_mutable_username();
  // @@protoc_insertion_point(field_mutable:UpLoadEchoResponse.username)
  return _s;
}
inline const std::string& UpLoadEchoResponse::_internal_username() const {
  return username_.Get();
}
inline void UpLoadEchoResponse::_internal_set_username(const std::string& value) {
  
  username_.Set(value, GetArenaForAllocation());
}
inline std::string* UpLoadEchoResponse::_internal_mutable_username() {
  
  return username_.Mutable(GetArenaForAllocation());
}
inline std::string* UpLoadEchoResponse::release_username() {
  // @@protoc_insertion_point(field_release:UpLoadEchoResponse.username)
  return username_.Release();
}
inline void UpLoadEchoResponse::set_allocated_username(std::string* username) {
  if (username != nullptr) {
    
  } else {
    
  }
  username_.SetAllocated(username, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (username_.IsDefault()) {
    username_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:UpLoadEchoResponse.username)
}

// int32 code = 5;
inline void UpLoadEchoResponse::clear_code() {
  code_ = 0;
}
inline int32_t UpLoadEchoResponse::_internal_code() const {
  return code_;
}
inline int32_t UpLoadEchoResponse::code() const {
  // @@protoc_insertion_point(field_get:UpLoadEchoResponse.code)
  return _internal_code();
}
inline void UpLoadEchoResponse::_internal_set_code(int32_t value) {
  
  code_ = value;
}
inline void UpLoadEchoResponse::set_code(int32_t value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:UpLoadEchoResponse.code)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_UpLoad_2eproto
